$ANSIBLE_VAULT;1.1;AES256
39656466333435356431646262626631383631313064616133373435383635306463363663333339
6236336463616266326630313336366638313831636433610a303336306539616632346131373363
34343236303130353564343136613535626535613664353765636437343738316562643637313032
3766653063643031320a643362346330633762613465623664623837626465323261346530653962
36643465666561656531303632636236613265653230643633316536326238343230313737613063
34366264386334346363313633623336346637613330653731623161633737613361336463333732
343136653432303032653237616438326563
