---

- name: Configure OSPF on cisco routers
  hosts: routers
  gather_facts: no

  tasks:
    - name: Deploy OSPF Configuration
      cisco.ios.ios_config:
        lines: "{{ lookup('template', '../templates/config_ospf.j2') }}"
      vars:
        ospf_process: "{{ ospf_processes[0] }}"
         