---

- name: ospf check
  hosts: routers
  gather_facts: no

  tasks:
    - name: show ospf
      cisco.ios.ios_command:
        commands:
          - show ip ospf nei
          - show ip route ospf
      register: output

    - name: show output
      debug:
        msg: "{{ output.stdout_lines }}"  